server:
  port: 9191
spring:   
 application:  
   name: API-GATEWAY
 zipkin:  
    base-url: http://localhost:9411
      
 cloud:
   gateway:
    routes:
      - id: MASTERDATA-SERVICE
        uri: lb://masterdata-service
        predicates:
          - Path=/olx/masterdata/**
      - id: ADVERTISE-SERVICE
        uri: lb://advertise-service
        predicates:
          - Path=/olx/advertise/**
      - id: LOGIN-SERVICE
        uri: lb://login-service
        predicates:
          - Path=/olx/auth/**
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    
    