server:
  port: 8000
  
spring:
 application:
    name: login-service
 zipkin:
    base-url: http://localhost:9411
 config:
    import:
     - configserver:http://localhost:8888
     
management:
  endpoints:
    web:
      exposure:
        include: "*"

      
eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
    instance:
      hostname: localhost
      
      
      