server:
  port: 7070
  
spring:
 application:
    name: masterdata-service
 zipkin:
    base-url: http://localhost:9411
 config:
    import:
     - configserver:http://localhost:8888    

management:
  endpoints:
    web:
      exposure:
        include: "*"
    
eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
    instance:
      hostname: localhost